#!/bin/bash
USAGE="Usage: ./docker-start [ test | dev | prod | down ]\n\n"\
"\ttest: run jest test watcher on backend\n"\
"\tdev: spin up backend in development mode\n"\
"\tprod: spin up backend in production mode\n"\
"\tdown: spin down all running containers and network\n"\
"\n\tGo Cibic.io!\n"
if [ -z $1 ]; then
	echo -e $USAGE;
elif [ $1 = "test" ]; then
	docker-compose down;
	docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d && \
	docker attach $(docker ps -q | head -n1);
elif [ $1 = "dev" ]; then
	docker-compose down;
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d;
elif [ $1 = "prod" ]; then
	docker-compose down;
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d;
elif [ $1 = "down" ]; then
	docker-compose down;
else
	echo -e $USAGE;
fi
