version: "3.6"
volumes:
  api_modules:
services:
  api:
    build: .
    entrypoint: npm run
    environment:
      - DEPLOY_ENV=development
      - API_PORT=${API_PORT}
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        source: api_modules
        target: /app/node_modules
    tty: true
    stdin_open: true
