version: "3.6"
volumes:
  api_modules:
  
services:
  api:
    build: .
    entrypoint: npm run
    environment:
      - DEPLOY_ENV=development
      - API_PORT=${API_PORT}
    volumes:
      - type: bind
        source: ./app
        target: /app
      - type: volume
        source: api_modules
        target: /app/node_modules
    depends_on:
      - db
    links:
      - db
    tty: true
    stdin_open: true
  db:
    image: postgres:12.2-alpine
    expose:
      - "5432"
    env_file:
      - .env
