#!/bin/bash
USAGE="Usage: ./docker-start [ test | e2e | dev | prod | down ]\n\n"\
"\ttest: run jest test watcher on backend unit tests\n"\
"\te2e: run jest/supertest end to end test on application\n"\
"\tdev: spin up backend in development mode\n"\
"\tprod: spin up backend in production mode\n"\
"\tdown: spin down all running containers and network\n"\
"\n\tGo Cibic.io!\n"

if [ -z $1 ]; then
	echo -e $USAGE;
elif [ $1 = "test" -o $1 = "e2e" ]; then
	if [ $USER = "ubuntu" ]; then
		echo "DO NOT RUN THIS ON EC2 IT WILL DESTROY THE DATABASE"
		exit;
	fi
	docker-compose down;
	docker-compose -f docker-compose.yml -f docker-compose.$1.yml up -d && \
	docker attach $(docker ps -q | head -n1);
	echo;
	echo "Running tests repeatedly creates lots of docker volumes!";
	echo "Enter 'Y' below if you find your hard drive running low on space.";
	echo "Hit enter to ignore for now";
	docker volume prune;
elif [ $1 = "dev" -o $1 = "prod" ]; then
	docker-compose down;
	docker-compose -f docker-compose.yml -f docker-compose.$1.yml up -d;
elif [ $1 = "down" ]; then
	docker-compose down;
else
	echo -e $USAGE;
fi
