#!/bin/bash
USAGE="Usage: ./docker-start [ test | dev | prod ]";
if [ -z $1 ]; then
	echo $USAGE;
elif [ $1 = "test" ]; then
	docker-compose -f docker-compose.yml -f docker-compose.test.yml up -d && \
	docker attach $(docker ps -q | head -n1);
elif [ $1 = "dev" ]; then
	docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d;
elif [ $1 = "prod" ]; then
	docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d;
else
	echo $USAGE;
fi
