#!/bin/bash
hecho () {
    echo "$0: ${@}"
}
hecho "This should only be ran when establishing a new Certificate Authority!"

ROOT_PSSWD=${ROOT_PSSWD:-'development'}
RSA_BITS=${RSA_BITS:-'4096'}
CA_NAME=${CA_NAME:-'Cibic_Io'}
SSL_TOOL=${SSL_TOOL:-'openssl'}

hecho "If asked for a password, type '${ROOT_PSSWD}' and hit enter."
hecho "Checking for tools..."
if [ `uname` != 'Linux' -a `uname` != 'Darwin']; then
    hecho
    hecho "                                  Oh No!"
    hecho "This is meant to be ran on a linux based os. You don't appear to be on one."
    hecho "If you are on windows, contact the dev team for guidance."
    hecho "If you are on a unix-like OS or OSX, go ahead and look over the script and modify as necessary,"
    hecho "then turn this safety check off. Cheers -smonroe"
    exit 1
fi

if [ -z `which ${SSL_TOOL}` ]; then
    hecho
    hecho "                                  Oh No!"
    hecho "This is meant to be ran on a machine with ${SSL_TOOL} installed. You don't appear to have this."
    hecho "If you have a similar tool installed, please read this guide and modify it accordingly,"
    hecho "or use your package manager to install ${SSL_TOOL}."
    exit 1
fi
hecho "Found all tools needed, continuing with generation..."

# The guide for this file located is at:
# https://deliciousbrains.com/ssl-certificate-authority-for-local-https-development/

# Here, we become out own Certificate Authority (CA)

# First, we need our private key
${SSL_TOOL} genrsa -des3 -out ${CA_NAME}.key ${RSA_BITS} || exit 1

# Then we generate the root certificate, replace these fields as needed.
echo -e "US\nCA\nSan Jose\n${CA_NAME}\nDev\nCibic.io\n.\nasdf\n${CA_NAME}\n" | ${SSL_TOOL} req -passin pass:$ROOT_PSSWD -x509 -new -nodes -key ${CA_NAME}.key -sha256 -days 365 -out ${CA_NAME}.pem || exit 1

# That gave us a .pem file, lets get a .der as well for good measure
${SSL_TOOL} x509 -inform PEM -outform DER -text -in ${CA_NAME}.pem -out ${CA_NAME}.der || exit 1

# Assuming we got this far, we're probably on linux and succesful, but lets check for full success and then do an install.

if [ -f ${CA_NAME}.key -a -f ${CA_NAME}.pem -a -f ${CA_NAME}.der ]; then
    hecho "Success! ${CA_NAME}.pem is your Root Certificate, install it on any necessary machines."
else
    hecho "Could not find all expected file, please read any error messages and try again"
    exit 1
fi
